spring.application.name=FileServiceHub
# ????????? ????? ???????
server.port=8081

# ?????????? ???? ??????
spring.datasource.initialize=false
spring.jpa.hibernate.ddl-auto=none

# ???????????
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG

